### ISSUE TITLE
Failed to build iOS app

### ISSUE THREAD

**Issue by caestrada** [DarshanGowda0/GeoFlutterFire#22]
I get the following build issue as soon as i build with the `geoflutterfire: ^2.0.3+2` package installed. Any help would be greatly appreciated.

Here is the log i get:
`                                                                      
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET cloud_firestore OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/carlose/flutter/.pub-cache/hosted/pub.dartlang.org/geoflutterfire-2.0.3+2/ios/Classes/Geo
    flutterfirePlugin.m:2:9: fatal error: 'geoflutterfire/geoflutterfire-Swift.h' file not found
    #import <geoflutterfire/geoflutterfire-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone X.
`

Here is my dependencies list:

dependencies:
  flutter:
    sdk: flutter
    cupertino_icons: ^0.1.2
    firebase_core: ^0.3.1+1
    cloud_firestore: ^0.9.7
    firebase_auth: ^0.8.2+1
    google_sign_in: ^3.2.4
    rxdart: ^0.20.0
    google_maps_flutter: ^0.4.0
    location: ^2.3.2
    geoflutterfire: ^2.0.3+2

**Comment by ondrejromancov** [comment]
I have the exact same problem

**Comment by caestrada** [comment]
@ondrejromancov did you figure out any workaround?

**Comment by ondrejromancov** [comment]
Unfortunately not

**Comment by ondrejromancov** [comment]
@caestrada Ok, I have solved the problem by following [this](https://stackoverflow.com/a/55293055/10391047)

**Comment by caestrada** [comment]
@ondrejromancov you got it!!! Thanks brother.

**Comment by DarshanGowda0** [comment]
@caestrada Can you close the issue if it's solved?

**Comment by spiderion** [comment]
> @caestrada I have just solved the problem by following [this](https://stackoverflow.com/a/55293055/10391047)

Worked for me
